from django.urls import path
from . import views

urlpatterns = [
    path('hello-world/', views.hello_world, name='hello_world'),
    path('get_all_courses/', views.get_all_courses, name='get_all_courses'),
    path('get_user_course/', views.get_user_course, name='get_user_course'),
    path('put_user_course/', views.put_user_course, name='put_user_course'),
    path('delete_user_course/', views.delete_user_course,
         name='delete_user_course'),
    path('login_user/', views.login_user, name='login_user'),
    path('signup_user/', views.signup_user, name='signup_user'),
    path('update_password/', views.update_password,
         name='update_password'),
    path('get_user_course_taken/', views.get_user_course_taken,
         name='get_user_course_taken'),
    path('put_user_course_taken/', views.put_user_course_taken,
         name='put_user_course_taken'),
    path('update_user_course_taken/', views.put_user_course_taken,
         name='update_user_course_taken'),
    path('get_subject_codes/', views.get_subject_codes,
         name='get_subject_codes'),
    path('get_catalog_numbers/', views.get_catalog_numbers,
         name='get_catalog_numbers'),
    path('get_all_sections/', views.get_all_sections,
         name='get_all_sections'),
    path('get_professor_course_taught/', views.get_professor_course_taught,
         name='get_professor_course_taught'),
    path('put_professor_course_taught/', views.put_professor_course_taught,
         name='put_professor_course_taught'),
    path('delete_professor_course_taught/', views.delete_professor_course_taught,
         name='delete_professor_course_taught'),
    path('get_students_for_professor/', views.get_students_for_professor,
         name='get_students_for_professor'),
]
