-- DROP TABLE Course CASCADE;
-- DROP TABLE CurrentSchedule CASCADE;
-- DROP TABLE LoginCredentials CASCADE;
-- DROP TABLE Prof CASCADE;
-- DROP TABLE Student CASCADE;
DROP TABLE CoursesTaken CASCADE;